TAROT_CARDS = [
    # Major Arcana
    {"id": 0,  "name": "The Fool",             "name_sv": "Narren",              "suit": "major",     "image": "major_00.jpg"},
    {"id": 1,  "name": "The Magician",          "name_sv": "Magikern",            "suit": "major",     "image": "major_01.jpg"},
    {"id": 2,  "name": "The High Priestess",    "name_sv": "Översteprässtinnan",  "suit": "major",     "image": "major_02.jpg"},
    {"id": 3,  "name": "The Empress",           "name_sv": "Kejsarinnan",         "suit": "major",     "image": "major_03.jpg"},
    {"id": 4,  "name": "The Emperor",           "name_sv": "Kejsaren",            "suit": "major",     "image": "major_04.jpg"},
    {"id": 5,  "name": "The Hierophant",        "name_sv": "Hierofanten",         "suit": "major",     "image": "major_05.jpg"},
    {"id": 6,  "name": "The Lovers",            "name_sv": "Älskarna",            "suit": "major",     "image": "major_06.jpg"},
    {"id": 7,  "name": "The Chariot",           "name_sv": "Vagnen",              "suit": "major",     "image": "major_07.jpg"},
    {"id": 8,  "name": "Strength",              "name_sv": "Styrkan",             "suit": "major",     "image": "major_08.jpg"},
    {"id": 9,  "name": "The Hermit",            "name_sv": "Eremiten",            "suit": "major",     "image": "major_09.jpg"},
    {"id": 10, "name": "Wheel of Fortune",      "name_sv": "Lyckans Hjul",        "suit": "major",     "image": "major_10.jpg"},
    {"id": 11, "name": "Justice",               "name_sv": "Rättvisan",           "suit": "major",     "image": "major_11.jpg"},
    {"id": 12, "name": "The Hanged Man",        "name_sv": "Den Hängde",          "suit": "major",     "image": "major_12.jpg"},
    {"id": 13, "name": "Death",                 "name_sv": "Döden",               "suit": "major",     "image": "major_13.jpg"},
    {"id": 14, "name": "Temperance",            "name_sv": "Måttligheten",        "suit": "major",     "image": "major_14.jpg"},
    {"id": 15, "name": "The Devil",             "name_sv": "Djävulen",            "suit": "major",     "image": "major_15.jpg"},
    {"id": 16, "name": "The Tower",             "name_sv": "Tornet",              "suit": "major",     "image": "major_16.jpg"},
    {"id": 17, "name": "The Star",              "name_sv": "Stjärnan",            "suit": "major",     "image": "major_17.jpg"},
    {"id": 18, "name": "The Moon",              "name_sv": "Månen",               "suit": "major",     "image": "major_18.jpg"},
    {"id": 19, "name": "The Sun",               "name_sv": "Solen",               "suit": "major",     "image": "major_19.jpg"},
    {"id": 20, "name": "Judgement",             "name_sv": "Domen",               "suit": "major",     "image": "major_20.jpg"},
    {"id": 21, "name": "The World",             "name_sv": "Världen",             "suit": "major",     "image": "major_21.jpg"},
    # Wands
    {"id": 22, "name": "Ace of Wands",          "name_sv": "Stavars Ess",         "suit": "wands",     "image": "wands_01.jpg"},
    {"id": 23, "name": "Two of Wands",          "name_sv": "Stavars Tvåa",        "suit": "wands",     "image": "wands_02.jpg"},
    {"id": 24, "name": "Three of Wands",        "name_sv": "Stavars Trea",        "suit": "wands",     "image": "wands_03.jpg"},
    {"id": 25, "name": "Four of Wands",         "name_sv": "Stavars Fyra",        "suit": "wands",     "image": "wands_04.jpg"},
    {"id": 26, "name": "Five of Wands",         "name_sv": "Stavars Femma",       "suit": "wands",     "image": "wands_05.jpg"},
    {"id": 27, "name": "Six of Wands",          "name_sv": "Stavars Sexa",        "suit": "wands",     "image": "wands_06.jpg"},
    {"id": 28, "name": "Seven of Wands",        "name_sv": "Stavars Sjua",        "suit": "wands",     "image": "wands_07.jpg"},
    {"id": 29, "name": "Eight of Wands",        "name_sv": "Stavars Åtta",        "suit": "wands",     "image": "wands_08.jpg"},
    {"id": 30, "name": "Nine of Wands",         "name_sv": "Stavars Nia",         "suit": "wands",     "image": "wands_09.jpg"},
    {"id": 31, "name": "Ten of Wands",          "name_sv": "Stavars Tia",         "suit": "wands",     "image": "wands_10.jpg"},
    {"id": 32, "name": "Page of Wands",         "name_sv": "Stavars Page",        "suit": "wands",     "image": "wands_11.jpg"},
    {"id": 33, "name": "Knight of Wands",       "name_sv": "Stavars Riddare",     "suit": "wands",     "image": "wands_12.jpg"},
    {"id": 34, "name": "Queen of Wands",        "name_sv": "Stavars Drottning",   "suit": "wands",     "image": "wands_13.jpg"},
    {"id": 35, "name": "King of Wands",         "name_sv": "Stavars Kung",        "suit": "wands",     "image": "wands_14.jpg"},
    # Cups
    {"id": 36, "name": "Ace of Cups",           "name_sv": "Bägares Ess",         "suit": "cups",      "image": "cups_01.jpg"},
    {"id": 37, "name": "Two of Cups",           "name_sv": "Bägares Tvåa",        "suit": "cups",      "image": "cups_02.jpg"},
    {"id": 38, "name": "Three of Cups",         "name_sv": "Bägares Trea",        "suit": "cups",      "image": "cups_03.jpg"},
    {"id": 39, "name": "Four of Cups",          "name_sv": "Bägares Fyra",        "suit": "cups",      "image": "cups_04.jpg"},
    {"id": 40, "name": "Five of Cups",          "name_sv": "Bägares Femma",       "suit": "cups",      "image": "cups_05.jpg"},
    {"id": 41, "name": "Six of Cups",           "name_sv": "Bägares Sexa",        "suit": "cups",      "image": "cups_06.jpg"},
    {"id": 42, "name": "Seven of Cups",         "name_sv": "Bägares Sjua",        "suit": "cups",      "image": "cups_07.jpg"},
    {"id": 43, "name": "Eight of Cups",         "name_sv": "Bägares Åtta",        "suit": "cups",      "image": "cups_08.jpg"},
    {"id": 44, "name": "Nine of Cups",          "name_sv": "Bägares Nia",         "suit": "cups",      "image": "cups_09.jpg"},
    {"id": 45, "name": "Ten of Cups",           "name_sv": "Bägares Tia",         "suit": "cups",      "image": "cups_10.jpg"},
    {"id": 46, "name": "Page of Cups",          "name_sv": "Bägares Page",        "suit": "cups",      "image": "cups_11.jpg"},
    {"id": 47, "name": "Knight of Cups",        "name_sv": "Bägares Riddare",     "suit": "cups",      "image": "cups_12.jpg"},
    {"id": 48, "name": "Queen of Cups",         "name_sv": "Bägares Drottning",   "suit": "cups",      "image": "cups_13.jpg"},
    {"id": 49, "name": "King of Cups",          "name_sv": "Bägares Kung",        "suit": "cups",      "image": "cups_14.jpg"},
    # Swords
    {"id": 50, "name": "Ace of Swords",         "name_sv": "Svärdets Ess",        "suit": "swords",    "image": "swords_01.jpg"},
    {"id": 51, "name": "Two of Swords",         "name_sv": "Svärdets Tvåa",       "suit": "swords",    "image": "swords_02.jpg"},
    {"id": 52, "name": "Three of Swords",       "name_sv": "Svärdets Trea",       "suit": "swords",    "image": "swords_03.jpg"},
    {"id": 53, "name": "Four of Swords",        "name_sv": "Svärdets Fyra",       "suit": "swords",    "image": "swords_04.jpg"},
    {"id": 54, "name": "Five of Swords",        "name_sv": "Svärdets Femma",      "suit": "swords",    "image": "swords_05.jpg"},
    {"id": 55, "name": "Six of Swords",         "name_sv": "Svärdets Sexa",       "suit": "swords",    "image": "swords_06.jpg"},
    {"id": 56, "name": "Seven of Swords",       "name_sv": "Svärdets Sjua",       "suit": "swords",    "image": "swords_07.jpg"},
    {"id": 57, "name": "Eight of Swords",       "name_sv": "Svärdets Åtta",       "suit": "swords",    "image": "swords_08.jpg"},
    {"id": 58, "name": "Nine of Swords",        "name_sv": "Svärdets Nia",        "suit": "swords",    "image": "swords_09.jpg"},
    {"id": 59, "name": "Ten of Swords",         "name_sv": "Svärdets Tia",        "suit": "swords",    "image": "swords_10.jpg"},
    {"id": 60, "name": "Page of Swords",        "name_sv": "Svärdets Page",       "suit": "swords",    "image": "swords_11.jpg"},
    {"id": 61, "name": "Knight of Swords",      "name_sv": "Svärdets Riddare",    "suit": "swords",    "image": "swords_12.jpg"},
    {"id": 62, "name": "Queen of Swords",       "name_sv": "Svärdets Drottning",  "suit": "swords",    "image": "swords_13.jpg"},
    {"id": 63, "name": "King of Swords",        "name_sv": "Svärdets Kung",       "suit": "swords",    "image": "swords_14.jpg"},
    # Pentacles
    {"id": 64, "name": "Ace of Pentacles",      "name_sv": "Pentagrammets Ess",   "suit": "pentacles", "image": "pentacles_01.jpg"},
    {"id": 65, "name": "Two of Pentacles",      "name_sv": "Pentagrammets Tvåa",  "suit": "pentacles", "image": "pentacles_02.jpg"},
    {"id": 66, "name": "Three of Pentacles",    "name_sv": "Pentagrammets Trea",  "suit": "pentacles", "image": "pentacles_03.jpg"},
    {"id": 67, "name": "Four of Pentacles",     "name_sv": "Pentagrammets Fyra",  "suit": "pentacles", "image": "pentacles_04.jpg"},
    {"id": 68, "name": "Five of Pentacles",     "name_sv": "Pentagrammets Femma", "suit": "pentacles", "image": "pentacles_05.jpg"},
    {"id": 69, "name": "Six of Pentacles",      "name_sv": "Pentagrammets Sexa",  "suit": "pentacles", "image": "pentacles_06.jpg"},
    {"id": 70, "name": "Seven of Pentacles",    "name_sv": "Pentagrammets Sjua",  "suit": "pentacles", "image": "pentacles_07.jpg"},
    {"id": 71, "name": "Eight of Pentacles",    "name_sv": "Pentagrammets Åtta",  "suit": "pentacles", "image": "pentacles_08.jpg"},
    {"id": 72, "name": "Nine of Pentacles",     "name_sv": "Pentagrammets Nia",   "suit": "pentacles", "image": "pentacles_09.jpg"},
    {"id": 73, "name": "Ten of Pentacles",      "name_sv": "Pentagrammets Tia",   "suit": "pentacles", "image": "pentacles_10.jpg"},
    {"id": 74, "name": "Page of Pentacles",     "name_sv": "Pentagrammets Page",  "suit": "pentacles", "image": "pentacles_11.jpg"},
    {"id": 75, "name": "Knight of Pentacles",   "name_sv": "Pentagrammets Riddare","suit": "pentacles", "image": "pentacles_12.jpg"},
    {"id": 76, "name": "Queen of Pentacles",    "name_sv": "Pentagrammets Drottning","suit":"pentacles","image": "pentacles_13.jpg"},
    {"id": 77, "name": "King of Pentacles",     "name_sv": "Pentagrammets Kung",  "suit": "pentacles", "image": "pentacles_14.jpg"},
]
